# docker run -d --rm --name mongo -p 27017:27017 -v mongodbdata:/data/db mongo

version: "4.4"

services:
  mongo:
    image: mongo
    container_name: mongo_play_catalog
    ports:
        - 27017:27017
    volumes:
        - mongodbdata:/data/db

  rabbitmq:
    image: rabbitmq:4.1.1-management
    container_name: rabbitmq_play_catalog
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - rabbitmqdata:/var/lib/rabbitmq
    hostname: rabbitmq

volumes:
  mongodbdata:
  rabbitmqdata:  